### ISSUE TITLE
One HAVE TO connect to a database to parse the SQL?

### ISSUE THREAD

**Issue by rotcx** [Giraphne/sqlvis#3]
One need not to connect to a database to parse the SQL?

**Comment by Giraphne** [comment]
Yes, this is true. If you just want to parse, there are lots of libraries that allow you to do so without connecting. However, for SQLVis we need to know the database schema. If you have any other suggestions to include the schema without extracting it from the database, feel free to post below.

**Comment by rotcx** [comment]
> 

but all the schema info needed for the user is included in the SQL code!!

**Comment by rotcx** [comment]
> If you just want to parse, there are lots of libraries that allow you to do so without connecting

for instance ?^_^

**Comment by Giraphne** [comment]
All the schema needed for parsing is indeed included in the query, but for the visualization we also use parts of the original schema that are not present in the query. For example, even if you only query SELECT pID FROM product we expand the view to allow you to see all columns of the product table, even the ones not in your query.

See the visualization examples in the README for more info.
